// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "305b8c15-f115-413f-adf4-121fe80ad094";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDegreeChange();
void onScheduleChange();
void onLEDChange();
void onServoBoolChange();

float water_d;
int degree;
CloudSchedule schedule;
bool lED;
bool servo_bool;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(water_d, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(degree, READWRITE, ON_CHANGE, onDegreeChange);
  ArduinoCloud.addProperty(schedule, READWRITE, ON_CHANGE, onScheduleChange);
  ArduinoCloud.addProperty(lED, READWRITE, ON_CHANGE, onLEDChange);
  ArduinoCloud.addProperty(servo_bool, READWRITE, ON_CHANGE, onServoBoolChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
